name: FTP Upload

on:
  push:
    paths:
      - '.dist/**'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload .dist via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server:   ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .dist
