name: Conditional Workflow

on:
  push:
    paths:
      - 'src/**'

jobs:
  conditional-run:
    runs-on: ubuntu-latest
    steps:
      - name: Only when src/ changes
        run: echo "Katalog src/ się zmienił!"
