name: Testy na wielu wersjach Pythona

on: push

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v4

      - name: Skonfiguruj Pythona ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Uruchom testy
        run: pytest
