name: Python Unit Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🚩 Pokaż zawartość workflow
  run: |
    echo "↪ Uruchamiam: $GITHUB_WORKFLOW"
    sed -n '1,30p' .github/workflows/python-tests.yml


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'           # zawsze najnowsze 3.*

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest
